import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "@/components/ui/footer";
import HeaderNavigation from "@/components/ui/header-navigation";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: {
    template: "Lollipop Finance | %s",
    default: "Lollipop Finance",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <header className="sticky top-0 z-50">
          <HeaderNavigation />
        </header>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
